name: app_essentials
description: Flutter App Essentials is a comprehensive package that aims to accelerate app development by providing essential features and utilities.
repository: https://github.com/ztalha6/app_essentials
issue_tracker: https://github.com/ztalha6/app_essentials/issues
version: 0.1.0
homepage: null

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.2.1+1
  dio_cache_interceptor: ^3.4.2
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.0
  flutter_staggered_animations: ^1.1.1
  get: ^4.6.5
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  image_cropper: ^5.0.0
  image_picker: ^0.8.9
  intl_phone_number_input: ^0.7.3+1
  package_info_plus: ^4.0.2
  pin_code_fields: ^7.4.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.1.2
  shimmer: ^3.0.0
  sign_in_with_apple: ^5.0.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
